

POST https://vini.digitalcombo.com.br/asaas-webhook
content-type: application/json

{
  "event": "PAYMENT_RECEIVED",
  "payment": {
    "object": "payment",
    "id": "pay_1950687716088529",
    "dateCreated": "2023-09-06",
    "customer": "cus_000005416198",
    "paymentLink": null,
    "value": 25,
    "netValue": 23.01,
    "originalValue": null,
    "interestValue": null,
    "description": "Pedido #40",
    "billingType": "BOLETO",
    "canBePaidAfterDueDate": true,
    "confirmedDate": "2023-09-06",
    "pixTransaction": null,
    "status": "RECEIVED",
    "dueDate": "2023-09-06",
    "originalDueDate": "2023-09-06",
    "paymentDate": "2023-09-06",
    "clientPaymentDate": "2023-09-06",
    "installmentNumber": null,
    "invoiceUrl": "https://sandbox.asaas.com/i/1950687716088529",
    "invoiceNumber": "03926883",
    "externalReference": "40",
    "deleted": false,
    "anticipated": false,
    "anticipable": false,
    "creditDate": "2023-09-06",
    "estimatedCreditDate": "2023-09-06",
    "transactionReceiptUrl": "https://sandbox.asaas.com/comprovantes/4292464891747460",
    "nossoNumero": "1171866",
    "bankSlipUrl": "https://sandbox.asaas.com/b/pdf/1950687716088529",
    "lastInvoiceViewedDate": null,
    "lastBankSlipViewedDate": null,
    "discount": {
      "value": 0,
      "limitDate": null,
      "dueDateLimitDays": 0,
      "type": "FIXED"
    },
    "fine": {
      "value": 0,
      "type": "FIXED"
    },
    "interest": {
      "value": 0,
      "type": "PERCENTAGE"
    },
    "split": [
      {
        "id": "f0762919-e04d-4fa8-8943-eb50e1d9a289",
        "walletId": "383bda33-3551-4868-901f-8ad33835aedb",
        "fixedValue": null,
        "percentualValue": 97,
        "totalValue": 22.31,
        "refusalReason": null,
        "status": "DONE"
      },
      {
        "id": "02263453-2475-40dc-af0b-32ac7579aa9b",
        "walletId": "188f7168-06f9-423b-85a3-905b9b277463",
        "fixedValue": null,
        "percentualValue": 3,
        "totalValue": 0.69,
        "refusalReason": null,
        "status": "DONE"
      }
    ],
    "postalService": false,
    "custody": null,
    "refunds": null
  }
}