

POST https://vini.digitalcombo.com.br/asaas-webhook
content-type: application/json

{
  "event": "PAYMENT_RECEIVED",
  "payment": {
    "object": "payment",
    "id": "pay_7666157882729830",
    "dateCreated": "2023-08-31",
    "customer": "cus_000005416198",
    "paymentLink": null,
    "value": 23,
    "netValue": 21.01,
    "originalValue": null,
    "interestValue": null,
    "description": "Pedido #26",
    "billingType": "PIX",
    "confirmedDate": "2023-08-31",
    "pixTransaction": "464e5478-3209-4626-a90e-ec96b4b0238f",
    "pixQrCodeId": "1b310da9-9314-4f09-9070-2071185c7fda",
    "status": "RECEIVED",
    "dueDate": "2023-09-03",
    "originalDueDate": "2023-09-03",
    "paymentDate": "2023-08-31",
    "clientPaymentDate": "2023-08-31",
    "installmentNumber": null,
    "invoiceUrl": "https://sandbox.asaas.com/i/7666157882729830",
    "invoiceNumber": "03901863",
    "externalReference": "26",
    "deleted": false,
    "anticipated": false,
    "anticipable": false,
    "creditDate": "2023-08-31",
    "estimatedCreditDate": "2023-08-31",
    "transactionReceiptUrl": "https://sandbox.asaas.com/comprovantes/2013980188534942",
    "nossoNumero": null,
    "bankSlipUrl": null,
    "lastInvoiceViewedDate": null,
    "lastBankSlipViewedDate": null,
    "discount": {
      "value": 0,
      "limitDate": null,
      "dueDateLimitDays": 0,
      "type": "FIXED"
    },
    "fine": {
      "value": 0,
      "type": "FIXED"
    },
    "interest": {
      "value": 0,
      "type": "PERCENTAGE"
    },
    "split": [
      {
        "id": "173ca000-7bdf-43a0-91be-454d273a5ff1",
        "walletId": "188f7168-06f9-423b-85a3-905b9b277463",
        "fixedValue": null,
        "percentualValue": 10,
        "totalValue": 2.1,
        "refusalReason": null,
        "status": "DONE"
      }
    ],
    "postalService": false,
    "custody": null,
    "refunds": null
  }
}