

POST https://vini.digitalcombo.com.br/asaas-webhook
content-type: application/json

{
  "event": "PAYMENT_RECEIVED",
  "payment": {
    "object": "payment",
    "id": "pay_2551995360183222",
    "dateCreated": "2023-09-06",
    "customer": "cus_000005416198",
    "paymentLink": null,
    "value": 40,
    "netValue": 38.01,
    "originalValue": null,
    "interestValue": null,
    "description": "Pedido #39",
    "billingType": "PIX",
    "confirmedDate": "2023-09-06",
    "pixTransaction": "e6e402a6-8228-4c30-98f4-c7c90a2f0b09",
    "pixQrCodeId": "43f505fc-016a-4777-bd8a-7e3a1f3426a2",
    "status": "RECEIVED",
    "dueDate": "2023-09-09",
    "originalDueDate": "2023-09-09",
    "paymentDate": "2023-09-06",
    "clientPaymentDate": "2023-09-06",
    "installmentNumber": null,
    "invoiceUrl": "https://sandbox.asaas.com/i/2551995360183222",
    "invoiceNumber": "03926770",
    "externalReference": "39",
    "deleted": false,
    "anticipated": false,
    "anticipable": false,
    "creditDate": "2023-09-06",
    "estimatedCreditDate": "2023-09-06",
    "transactionReceiptUrl": "https://sandbox.asaas.com/comprovantes/6614947756676677",
    "nossoNumero": null,
    "bankSlipUrl": null,
    "lastInvoiceViewedDate": null,
    "lastBankSlipViewedDate": null,
    "discount": {
      "value": 0,
      "limitDate": null,
      "dueDateLimitDays": 0,
      "type": "FIXED"
    },
    "fine": {
      "value": 0,
      "type": "FIXED"
    },
    "interest": {
      "value": 0,
      "type": "PERCENTAGE"
    },
    "postalService": false,
    "custody": null,
    "refunds": null
  }
}